# Generated by Django 5.1.15 on 2026-08-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookmark_download_review'),
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='departments',
            field=models.ManyToManyField(blank=True, related_name='books', to='departments.department'),
        ),
    ]
