# Generated by Django 5.1.15 on 2026-08-07 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_savednote'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='content_type',
            field=models.CharField(blank=True, choices=[('textbook', 'Textbook / Book'), ('learning_material', 'Learning Material'), ('resource', 'Resource'), ('past_exam_paper', 'Past Examination Paper')], max_length=32, null=True),
        ),
    ]
